printer_connect:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: octoprint
    profile_name:
      required: false
      selector:
        text:
    port:
      required: false
      selector:
        text:
    baudrate:
      required: false
      selector:
        select:
          options:
            - "9600"
            - "19200"
            - "38400"
            - "57600"
            - "115200"
            - "230400"
            - "250000"

set_tool_temperature:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: octoprint
    tool_temperature:
      required: true
      selector:
        number:
          min: 0
          max: 400
          step: 1
          unit_of_measurement: "°C"

set_bed_temperature:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: octoprint
    bed_temperature:
      required: true
      selector:
        number:
          min: 0
          max: 150
          step: 1
          unit_of_measurement: "°C"

move_tool:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: octoprint
    x_offset:
      required: false
      selector:
        number:
          min: -500
          max: 500
          step: 0.1
          unit_of_measurement: "mm"
    y_offset:
      required: false
      selector:
        number:
          min: -500
          max: 500
          step: 0.1
          unit_of_measurement: "mm"
    z_offset:
      required: false
      selector:
        number:
          min: -500
          max: 500
          step: 0.1
          unit_of_measurement: "mm"

set_position:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: octoprint
    x_position:
      required: false
      selector:
        number:
          min: 0
          max: 500
          step: 0.1
          unit_of_measurement: "mm"
    y_position:
      required: false
      selector:
        number:
          min: 0
          max: 500
          step: 0.1
          unit_of_measurement: "mm"
    z_position:
      required: false
      selector:
        number:
          min: 0
          max: 500
          step: 0.1
          unit_of_measurement: "mm"
